# -*- coding: utf-8 -*-
"""Generic project utilities.

Only infrastructure-level helpers belong here. KG, retrieval, answering,
agent, graph, and protocol logic must remain in their domain modules.
"""

from .config_loader import (
    DEFAULT_CONFIG_DIR,
    DEFAULT_CONFIG_FILES,
    ConfigLoader,
    apply_env_overrides,
    deep_merge,
    dump_config_json,
    fill_default_config,
    get_config_dir,
    get_config_value,
    get_default_config,
    has_config_value,
    load_all_configs,
    load_config,
    load_yaml_file,
    merge_configs,
    parse_bool,
    require_valid_config,
    save_yaml_file,
    set_config_value,
    validate_config,
)
from .exceptions import (
    ConfigurationError,
    ConfigurationValidationError,
    DependencyUnavailableError,
    KGRAGError,
    OperationTimeoutError,
    PermissionDeniedError,
    ResourceNotFoundError,
)
from .logger import (
    clear_handlers,
    get_default_logger,
    get_logger,
    log_exception,
    log_node_end,
    log_node_error,
    log_node_start,
    parse_log_level,
    reset_default_logger,
    setup_logger,
    truncate_text,
)
from .paths import (
    PROJECT_ROOT_ENV,
    PathBoundaryError,
    ensure_directory,
    ensure_within_directory,
    get_project_root,
    relative_to_project,
    resolve_project_path,
)

__all__ = [
    "DEFAULT_CONFIG_DIR",
    "DEFAULT_CONFIG_FILES",
    "ConfigLoader",
    "load_config",
    "load_all_configs",
    "load_yaml_file",
    "save_yaml_file",
    "get_config_dir",
    "get_default_config",
    "fill_default_config",
    "apply_env_overrides",
    "get_config_value",
    "set_config_value",
    "has_config_value",
    "deep_merge",
    "merge_configs",
    "validate_config",
    "require_valid_config",
    "dump_config_json",
    "parse_bool",
    "get_logger",
    "setup_logger",
    "get_default_logger",
    "reset_default_logger",
    "clear_handlers",
    "log_exception",
    "log_node_start",
    "log_node_end",
    "log_node_error",
    "truncate_text",
    "parse_log_level",
    "PROJECT_ROOT_ENV",
    "PathBoundaryError",
    "get_project_root",
    "resolve_project_path",
    "ensure_directory",
    "ensure_within_directory",
    "relative_to_project",
    "KGRAGError",
    "ConfigurationError",
    "ConfigurationValidationError",
    "DependencyUnavailableError",
    "ResourceNotFoundError",
    "PermissionDeniedError",
    "OperationTimeoutError",
]
