# -*- coding: utf-8 -*-
"""KG-RAG Agent 离线数据构建层。"""

from __future__ import annotations

from .data_loader import (
    DataLoader,
    DataLoaderPaths,
    build_alias_map,
    build_entities,
    build_relations,
    load_entity_index,
    load_id_map,
    load_path_graph,
    iter_path_graph,
    load_relation_index,
    parse_path_graph_line,
    process_raw_data,
    save_triples_csv,
)
from .graph_builder import (
    GraphBuilder,
    GraphBuilderPaths,
    build_graph,
    build_networkx_graph,
    get_graph_stats,
    load_triples_csv,
    iter_triples_csv,
    save_graph_pickle,
    save_graph_stats,
)
from .manifest import (
    MANIFEST_FILENAME,
    artifact_record,
    build_manifest,
    load_manifest,
    sha256_file,
    validate_manifest,
    write_manifest_copies,
)
from .paths import (
    PipelinePaths,
    get_project_root,
    normalize_profile,
    resolve_project_path,
)
from .pipeline import DataPipeline, build_all
from .schemas import BuildOptions, StageResult, new_build_id
from .vector_builder import (
    VectorBuilder,
    VectorBuilderPaths,
    build_vector_store,
    deduplicate_entities,
    extract_entities_from_graph,
    load_entities_from_best_source,
    load_entities_json,
    load_graph_pickle,
    normalize_aliases,
    normalize_entity_record,
    normalize_node_record,
    write_entities_to_vector_store,
)

__all__ = [
    "BuildOptions",
    "DataPipeline",
    "PipelinePaths",
    "StageResult",
    "new_build_id",
    "build_all",
    "MANIFEST_FILENAME",
    "artifact_record",
    "build_manifest",
    "load_manifest",
    "sha256_file",
    "validate_manifest",
    "write_manifest_copies",
    "get_project_root",
    "normalize_profile",
    "resolve_project_path",
    "DataLoader",
    "DataLoaderPaths",
    "load_id_map",
    "load_entity_index",
    "load_relation_index",
    "load_path_graph",
    "iter_path_graph",
    "parse_path_graph_line",
    "build_entities",
    "build_relations",
    "build_alias_map",
    "save_triples_csv",
    "process_raw_data",
    "GraphBuilder",
    "GraphBuilderPaths",
    "load_triples_csv",
    "iter_triples_csv",
    "build_networkx_graph",
    "save_graph_pickle",
    "get_graph_stats",
    "save_graph_stats",
    "build_graph",
    "VectorBuilder",
    "VectorBuilderPaths",
    "load_entities_json",
    "load_graph_pickle",
    "extract_entities_from_graph",
    "load_entities_from_best_source",
    "normalize_entity_record",
    "normalize_node_record",
    "normalize_aliases",
    "deduplicate_entities",
    "write_entities_to_vector_store",
    "build_vector_store",
]
